
import NavBar from '../components/Navbar'
import './globals.css'
import { Inter ,Poppins,Urbanist, Inconsolata, Lora} from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const urbanist = Urbanist({ subsets: ['latin'] })



export const inconsolata = Inconsolata({
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-inconsolata',
  fallback: ['Courier New', 'Courier', 'monospace'],
  subsets: ['latin'],
});

export const lora = Lora({
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-lora',
  fallback: ['Times New Roman', 'Times', 'serif'],
  subsets: ['latin'],
});



export const metadata = {
  title: 'Virtual Group of Companies',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html  lang="en">
      <body className={`${urbanist.variable} ${inter.variable} ${inconsolata.variable} ${lora.variable}`}>
      <NavBar/>
      
      <div className='  mx-auto '>
        {children}
      
        </div>
       <h1 className='text-2xl item-center flex justify-center'> Footer </h1>
        </body>
    </html>
  )
}
